### ISSUE TITLE
Crash loop on v 1.0.5 with Thaumic History

### ISSUE THREAD

**Issue by dreamwisdom** [Beyond-Reality/BR-DC#1]
I made a research paper with 9 lost fragment in a translocator crafting grid. It gave me an unknown research. After putting it in the research table I got kick and I am not able to connect anymore.

``` java
java.lang.NullPointerException
    at net.werwolv.th.client.render.RenderItemParchment.renderResearchNotes(RenderItemParchment.java:208)
```

http://pastebin.com/gi4EhtV2

**Comment by Dyonovan** [comment]
This is a known issue with Thaumic History and one of the reasons the mod will be removed next udpdate.
